//// [tests/cases/compiler/redeclareParameterInCatchBlock.ts] ////

=== redeclareParameterInCatchBlock.ts ===
try {

} catch(e) {
>e : any
>  : ^^^

    const e = null;
>e : any
>  : ^^^
}

try {

} catch(e) {
>e : any
>  : ^^^

    let e;
>e : any
>  : ^^^
}

try {

} catch ([a, b]) {
>a : any
>  : ^^^
>b : any
>  : ^^^

    const [c, b] = [0, 1];
>c : number
>  : ^^^^^^
>b : number
>  : ^^^^^^
>[0, 1] : [number, number]
>       : ^^^^^^^^^^^^^^^^
>0 : 0
>  : ^
>1 : 1
>  : ^
}

try {

} catch ({ a: x, b: x }) {
>a : any
>  : ^^^
>x : any
>  : ^^^
>b : any
>  : ^^^
>x : any
>  : ^^^

}

try {

} catch(e) {
>e : any
>  : ^^^

    function test() {
>test : () => void
>     : ^^^^^^^^^^

        let e;
>e : any
>  : ^^^
    }
}

